[package]
name = "connector"
version = "0.1.0"
edition = "2021"

[features]
default = ["binancefutures", "bybit"]
binancefutures = []
bybit = []

[dependencies]
hftbacktest = { path = "../hftbacktest", version = "0.4.0" }
tracing = "0.1.40"
anyhow = "1.0.79"
thiserror = "1.0.57"
bincode = "2.0.0-rc.3"
chrono = { version = "0.4.33", optional = true }
serde = { version = "1.0.196", features = ["derive"], optional = true }
serde_json = { version = "1.0.113", optional = true }
tokio = { version = "1.35.1", features = ["full"], optional = true }
tokio-tungstenite = { version = "0.23.1", features = ["rustls-tls-native-roots"], optional = true }
reqwest = { version = "0.12.3", default-features = false, features = ["json", "rustls-tls-native-roots"], optional = true }
futures-util = { version = "0.3.30", optional = true }
sha2 = { version = "0.11.0-pre.3", optional = true }
hmac = { version = "0.13.0-pre.3", optional = true }
rand = { version = "0.8.5", optional = true }
uuid = { version = "1.8.0", features = ["v4"], optional = true }
iceoryx2 = { version = "0.3.0", optional = true }
